/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package bbSuperMercado;

import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author bruno
 */
public class cadastrarProdutoPanel extends javax.swing.JPanel {

    /**
     * Creates new form cadastrarProdutoPanel
     */
    public cadastrarProdutoPanel(JFrame mainFrame) {
        initComponents();
        
        mainFrame.setTitle("BB Super-Mercado | $Gerente - Cadastrar Produto");        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelCadastroProduto = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        labelQuantidade = new javax.swing.JLabel();
        labelPreco = new javax.swing.JLabel();
        labelSetor = new javax.swing.JLabel();
        tfSetor = new javax.swing.JTextField();
        btnSelectSetor = new javax.swing.JButton();
        tfNome = new javax.swing.JTextField();
        tfQuantidade = new javax.swing.JTextField();
        tfPreco = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();

        labelCadastroProduto.setText("Cadastro de Produto");

        labelNome.setText("Nome:");

        labelQuantidade.setText("Quantidade (un):");

        labelPreco.setText("Preço (un):");

        labelSetor.setText("Setor:");

        tfSetor.setEditable(false);
        tfSetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSetorActionPerformed(evt);
            }
        });

        btnSelectSetor.setText("Selecionar");
        btnSelectSetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectSetorActionPerformed(evt);
            }
        });

        tfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeActionPerformed(evt);
            }
        });

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelPreco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfPreco, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                        .addGap(260, 260, 260))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCadastrar)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelQuantidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfNome))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelCadastroProduto)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelSetor)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnSelectSetor))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addComponent(labelCadastroProduto)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSetor)
                    .addComponent(tfSetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelectSetor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPreco)
                    .addComponent(tfPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelQuantidade)
                    .addComponent(tfQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar)
                    .addComponent(btnVoltar))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jDialogError(String errorString, java.awt.event.ActionEvent evt){
        JDialog dialog = new JDialog();
        dialog.setSize(250, 100);
        dialog.setLayout(new FlowLayout());
        dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);

        JLabel errorLabel = new JLabel(errorString);
        JButton btnOk = new JButton("OK");                    

        btnOk.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {                
                dialog.dispose();
                switch(errorString){
                    case "Preço inválido! Não é permitido Caracteres!":
                        tfPreco.setText("");
                        break;
                        
                    case "Quantidade inválida! Não é permitido valores decimais!":
                        tfQuantidade.setText("");
                        break;
                        
                    case "Nome do produto muito grande! Máx 30 caracteres!":
                        tfNome.setText("");
                        break;
                }                
            }
        }); 

        dialog.setTitle("Operação inválida");

        dialog.add(errorLabel);
        dialog.add(btnOk);  

        dialog.setLocationRelativeTo(SwingUtilities.getWindowAncestor(this));

        dialog.setModal(true);
        dialog.setVisible(true);

        //atualizar tela
        JFrame currentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        currentFrame.remove(((JButton)evt.getSource()).getParent());        
        currentFrame.add(((JButton)evt.getSource()).getParent());
        currentFrame.revalidate();
        currentFrame.repaint();
    }
    
    private void btnSelectSetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectSetorActionPerformed
        // TODO add your handling code here:
        
        //JFrame currentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        //JDialog dialog = new setoresDialog(currentFrame, true);        
        
        //selecionar setor
        //como pego qual botão selecionei?
        String[] setoresStrings = {"Alimentos", "Limpeza", "Acougue", "Bebidas", "Hortifruti", "Padaria"};
        String setor = (String)JOptionPane.showInputDialog(null, "Setores:", 
                "Selecione o Setor", JOptionPane.QUESTION_MESSAGE, null, setoresStrings, setoresStrings[2]);
        //System.out.println(n);
        tfSetor.setText(setor.toLowerCase());
        //atualizar tela        
        /*currentFrame.remove(((JButton)evt.getSource()).getParent());        
        currentFrame.add(((JButton)evt.getSource()).getParent());
        currentFrame.revalidate();
        currentFrame.repaint();*/
    }//GEN-LAST:event_btnSelectSetorActionPerformed

    private void tfSetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSetorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSetorActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
        JFrame currentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        
        boolean produtoCorreto = true;
        
        String nome = "";
        int quantidade = 0;
        float preco = 0;
        String setor = "";
        String errorString = "";
        //Nome
        try{
            nome = tfNome.getText();
            if(nome.length() > 30){
                errorString = "Nome do produto muito grande! Máx 30 caracteres!";
                throw new RuntimeException(errorString);
            }
        }catch(RuntimeException e){ //erro de quantidade            
            jDialogError(errorString, evt);
            produtoCorreto = false;
        }
        
        //Preco
        try{
            preco = Float.parseFloat(tfPreco.getText());
        }catch(NumberFormatException e){
            errorString = "Preço inválido! Não é permitido Caracteres!";
            jDialogError(errorString, evt);
            produtoCorreto = false;
        }
        
        //Quantidade
        try{
            quantidade = Integer.parseInt(tfQuantidade.getText());
        }catch(NumberFormatException e){
            errorString = "Quantidade inválida! Não é permitido valores decimais!";
            jDialogError(errorString, evt);
            produtoCorreto = false;
        }
        
        if(produtoCorreto){
            Produto produto = new Produto(nome, quantidade, preco);

            setor = tfSetor.getText();

            Gerente.cadastrarProduto(produto, setor);

            JDialog dialog = new JDialog();
                dialog.setSize(250, 100);
                dialog.setLayout(new FlowLayout());
                dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);

                JLabel labelAddedProduto = new JLabel("Produto "+nome+" adicionado com Sucesso!");
                JButton btnOk = new JButton("OK");                    

                btnOk.addActionListener(new ActionListener(){
                    @Override
                    public void actionPerformed(ActionEvent e) {                
                        dialog.dispose();
                        tfNome.setText("");
                        tfPreco.setText("");
                        tfQuantidade.setText("");
                        tfSetor.setText("");

                        //atualizar tela
                        currentFrame.remove(((JButton)evt.getSource()).getParent());        
                        currentFrame.add(((JButton)evt.getSource()).getParent());
                        currentFrame.revalidate();
                        currentFrame.repaint();
                    }
                }); 

                dialog.setTitle("Produto adicionado!");

                dialog.add(labelAddedProduto);
                dialog.add(btnOk);  

                dialog.setLocationRelativeTo(SwingUtilities.getWindowAncestor(this));

                dialog.setModal(true);
                dialog.setVisible(true);
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void tfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        JFrame currentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        currentFrame.remove(((JButton)evt.getSource()).getParent());
        
        JPanel opcoesGerente = new opcoesGerente(currentFrame);
        
        currentFrame.add(opcoesGerente);
        currentFrame.revalidate();
        currentFrame.repaint();
    }//GEN-LAST:event_btnVoltarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnSelectSetor;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel labelCadastroProduto;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelPreco;
    private javax.swing.JLabel labelQuantidade;
    private javax.swing.JLabel labelSetor;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfPreco;
    private javax.swing.JTextField tfQuantidade;
    private javax.swing.JTextField tfSetor;
    // End of variables declaration//GEN-END:variables
}
