/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package bbSuperMercado;

import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Collections;
import java.util.Iterator;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author bruno
 */
public class finalizarCarrinhoPanel extends javax.swing.JPanel {

    /**
     * Creates new form finalizarCarrinhoPanel
     */
    public finalizarCarrinhoPanel(JFrame mainFrame) {        
        
        float valorTotalCompra = 0;
        Iterator<Produto> itCarrinho = Cliente.carrinho.iterator();
        
        Collections.shuffle(App.funcionarios);

        int i = 0;
        for (Caixa caixa : App.caixas) {
            caixa.setFuncionario(App.funcionarios.get(i));
            i++;
        }
        
        while(itCarrinho.hasNext()) {
            Produto produto = itCarrinho.next();
            valorTotalCompra += produto.getPrecoUni()* produto.getQuantidadeCompra();
        }
        //System.out.println(App.caixas.get(0).getFuncionario().getNome());        
        
        initComponents();
        
        mainFrame.setTitle("BB Super-Mercado | $Cliente - Finalizar carrinho");

        btnFuncionario1.setText("Caixa 1 - " + App.caixas.get(0).getFuncionario().getNome());
        btnFuncionario2.setText("Caixa 2 - " + App.caixas.get(1).getFuncionario().getNome());
        btnFuncionario3.setText("Caixa 3 - " + App.caixas.get(2).getFuncionario().getNome());
        labelValorCompra.setText("Valor da compra: R$ " + valorTotalCompra);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnFuncionario1 = new javax.swing.JButton();
        btnFuncionario2 = new javax.swing.JButton();
        btnFuncionario3 = new javax.swing.JButton();
        labelValorCompra = new javax.swing.JLabel();
        btnVoltarCompras = new javax.swing.JButton();

        jLabel2.setText("Escolha o funcionário para finalizar a compra:");

        btnFuncionario1.setText("$name");
        btnFuncionario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFuncionario1ActionPerformed(evt);
            }
        });

        btnFuncionario2.setText("$name");
        btnFuncionario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFuncionario2ActionPerformed(evt);
            }
        });

        btnFuncionario3.setText("$name");
        btnFuncionario3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFuncionario3ActionPerformed(evt);
            }
        });

        labelValorCompra.setText("Valor da compra: ");

        btnVoltarCompras.setText("Voltar para as compras");
        btnVoltarCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarComprasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(btnVoltarCompras)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnFuncionario3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                        .addComponent(btnFuncionario2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFuncionario1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(labelValorCompra))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelValorCompra)
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFuncionario1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFuncionario2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFuncionario3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addComponent(btnVoltarCompras)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void dialogCompraFinalizada(float valorTotalCompra, java.awt.event.ActionEvent evt){
        
        //atualizar tela
        JFrame currentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        currentFrame.remove(((JButton)evt.getSource()).getParent());  
        
        Cliente.corredorAtual = 0;
        Cliente.setorAtual = null;
        
        JFrame loginFrame = new loginFrame();
        
        currentFrame.dispose();
        loginFrame.setVisible(true);
        
        //JDialog
        JDialog dialog = new JDialog();
        dialog.setSize(250, 130);
        dialog.setLayout(new FlowLayout());
        dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        
        JLabel labelCompraFinalizada = new JLabel("Compra finalizada com sucesso!");
        JLabel labelValorTotalCompra = new JLabel("Valor: R$ " + valorTotalCompra);
        JButton btnOk = new JButton("OK");                    
        
        btnOk.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {                
                dialog.dispose();                
            }
        }); 
        
        dialog.setTitle("Obrigado, volte sempre!");
        
        dialog.add(labelCompraFinalizada);
        dialog.add(labelValorTotalCompra);  
        dialog.add(btnOk);
        
        dialog.setLocationRelativeTo(SwingUtilities.getWindowAncestor(this));
        
        dialog.setModal(true);
        dialog.setVisible(true);             
    }
    
    private void btnFuncionario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFuncionario1ActionPerformed
        // TODO add your handling code here:
        float valorTotalCompra = App.caixas.get(0).finalizarCompra();
        dialogCompraFinalizada(valorTotalCompra, evt);
    }//GEN-LAST:event_btnFuncionario1ActionPerformed

    private void btnFuncionario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFuncionario2ActionPerformed
        // TODO add your handling code here:
        float valorTotalCompra = App.caixas.get(1).finalizarCompra();
        dialogCompraFinalizada(valorTotalCompra, evt);
    }//GEN-LAST:event_btnFuncionario2ActionPerformed

    private void btnFuncionario3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFuncionario3ActionPerformed
        // TODO add your handling code here:
        float valorTotalCompra = App.caixas.get(2).finalizarCompra();
        dialogCompraFinalizada(valorTotalCompra, evt);
    }//GEN-LAST:event_btnFuncionario3ActionPerformed

    private void btnVoltarComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarComprasActionPerformed
        // TODO add your handling code here:        
        JFrame currentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        currentFrame.remove(((JButton)evt.getSource()).getParent());
        
        JPanel consultaSetorPanel = new consultaSetorPanel(currentFrame);
        
        currentFrame.add(consultaSetorPanel);
        currentFrame.revalidate();
        currentFrame.repaint();
    }//GEN-LAST:event_btnVoltarComprasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFuncionario1;
    private javax.swing.JButton btnFuncionario2;
    private javax.swing.JButton btnFuncionario3;
    private javax.swing.JButton btnVoltarCompras;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelValorCompra;
    // End of variables declaration//GEN-END:variables
}
