/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package bbSuperMercado;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author bruno
 */
public class opcoesGerente extends javax.swing.JPanel {

    /**
     * Creates new form opcoesGerente
     */
    public opcoesGerente(JFrame mainFrame) {
        initComponents();
        
        mainFrame.setTitle("BB Super-Mercado | $Gerente - Opções");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVoltarParaLogin = new javax.swing.JButton();
        btnCadastrarProduto = new javax.swing.JButton();
        btnVendasGerais = new javax.swing.JButton();
        btnAltEstoque = new javax.swing.JButton();
        btnVendaFuncionarios = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        btnVoltarParaLogin.setText("Voltar para o Login");
        btnVoltarParaLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarParaLoginActionPerformed(evt);
            }
        });

        btnCadastrarProduto.setText("Cadastrar Produto");
        btnCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarProdutoActionPerformed(evt);
            }
        });

        btnVendasGerais.setText("Vendas Gerais");
        btnVendasGerais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendasGeraisActionPerformed(evt);
            }
        });

        btnAltEstoque.setText("Alteração de Estoque");
        btnAltEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltEstoqueActionPerformed(evt);
            }
        });

        btnVendaFuncionarios.setText("Venda por Funcionário");
        btnVendaFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendaFuncionariosActionPerformed(evt);
            }
        });

        jLabel1.setText("Gerar relatórios");

        jLabel2.setText("CRUD");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVoltarParaLogin)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCadastrarProduto)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAltEstoque)
                            .addComponent(btnVendasGerais)
                            .addComponent(btnVendaFuncionarios)
                            .addComponent(jLabel1))))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrarProduto)
                    .addComponent(btnVendasGerais))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAltEstoque)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVendaFuncionarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(btnVoltarParaLogin)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarParaLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarParaLoginActionPerformed
        // TODO add your handling code here:
        JFrame loginFrame = new loginFrame();
        JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);

        Cliente.corredorAtual = 0;
        Cliente.setorAtual = null;

        loginFrame.setVisible(true);
        topFrame.setVisible(false);
    }//GEN-LAST:event_btnVoltarParaLoginActionPerformed

    private void btnCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarProdutoActionPerformed
        // TODO add your handling code here:
        JFrame currentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        currentFrame.remove(((JButton)evt.getSource()).getParent());
        
        JPanel cadastrarProdutoPanel = new cadastrarProdutoPanel(currentFrame);
        
        currentFrame.add(cadastrarProdutoPanel);
        currentFrame.revalidate();
        currentFrame.repaint();
    }//GEN-LAST:event_btnCadastrarProdutoActionPerformed

    private void btnVendasGeraisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendasGeraisActionPerformed
        // TODO add your handling code here:
        JFrame currentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        currentFrame.remove(((JButton)evt.getSource()).getParent());
        
        JPanel relatorioVendasGeraisPanel = new relatorioVendasGeraisPanel(currentFrame);
        
        currentFrame.add(relatorioVendasGeraisPanel);
        currentFrame.revalidate();
        currentFrame.repaint();
    }//GEN-LAST:event_btnVendasGeraisActionPerformed

    private void btnVendaFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendaFuncionariosActionPerformed
        // TODO add your handling code here:
        JFrame currentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        currentFrame.remove(((JButton)evt.getSource()).getParent());
        
        JPanel relatorioVendaFuncioPanel = new relatorioVendaFuncioPanel(currentFrame);
        
        currentFrame.add(relatorioVendaFuncioPanel);
        currentFrame.revalidate();
        currentFrame.repaint();
    }//GEN-LAST:event_btnVendaFuncionariosActionPerformed

    private void btnAltEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltEstoqueActionPerformed
        // TODO add your handling code here:
        JFrame currentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        currentFrame.remove(((JButton)evt.getSource()).getParent());
        
        JPanel relatorioEstoquePanel = new relatorioEstoquePanel(currentFrame);
        
        currentFrame.add(relatorioEstoquePanel);
        currentFrame.revalidate();
        currentFrame.repaint();
    }//GEN-LAST:event_btnAltEstoqueActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAltEstoque;
    private javax.swing.JButton btnCadastrarProduto;
    private javax.swing.JButton btnVendaFuncionarios;
    private javax.swing.JButton btnVendasGerais;
    private javax.swing.JButton btnVoltarParaLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
