/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package bbSuperMercado;

import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author bruno
 */
public class relatorioVendaFuncioPanel extends javax.swing.JPanel {

    /**
     * Creates new form relatorioVendaFuncioPanel
     */
    public relatorioVendaFuncioPanel(JFrame mainFrame) {
        initComponents();
        
        mainFrame.setTitle("BB Super-Mercado | $Gerente - Gerar relatório de vendas por funcionário");
        createListVendasFuncionario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVoltarParaLogin = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listVendasFuncionario = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();

        btnVoltarParaLogin.setText("Voltar");
        btnVoltarParaLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarParaLoginActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(listVendasFuncionario);

        jLabel1.setText("Funcionários");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnVoltarParaLogin)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVoltarParaLogin)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void createListVendasFuncionario(){
        DefaultListModel listModel = new DefaultListModel();
        
        for(Funcionario funcionario: App.funcionarios){
            listModel.addElement(funcionario);
        }
        
        listVendasFuncionario.setModel(listModel);
    }
    
    private void btnVoltarParaLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarParaLoginActionPerformed
        // TODO add your handling code here:
        JFrame currentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        currentFrame.remove(((JButton)evt.getSource()).getParent());
        
        JPanel opcoesGerente = new opcoesGerente(currentFrame);
        
        currentFrame.add(opcoesGerente);
        currentFrame.revalidate();
        currentFrame.repaint();
    }//GEN-LAST:event_btnVoltarParaLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVoltarParaLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listVendasFuncionario;
    // End of variables declaration//GEN-END:variables
}
